/**
 * BGM & SFX `entry.backend` for the Host ToolRegistry.
 *
 * Humans and AI share the generation + audio-project tools. Packaged library
 * search/attach has been removed; generated bytes land in the game via
 * `generate-audio-assets` / `save-generated-audio`.
 *
 * Sandbox contract: secrets + project root arrive via per-call `ctx.env`
 * (filtered to the manifest's `requestedEnv`). `ctx.cwd` is the plugin dir.
 */

import { createHash } from 'node:crypto';
import { existsSync } from 'node:fs';
import { readFile } from 'node:fs/promises';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import {
  attachGeneratedAudio,
  BgmError,
  type AudioKind,
  gameRoot,
} from './core.ts';
import { inspectAudioEvents } from './audio-event-inspector.ts';
import {
  authorMusic,
  defineAttenuation,
  defineBus,
  defineGameSync,
  migrateAudioProjectDraft,
  patchAudioProject,
  readAppliedAudioProject,
  readAudioProject,
  writeAppliedAudioProject,
  type PatchAudioProjectArgs,
} from './audio-project-store.ts';
import { cooldownScopeWarning } from '../shared/event-archetypes.ts';
import { compileAudioRuntime } from './audio-runtime-compiler.ts';
import { verifyAudioProject } from './audio-project-verify.ts';
import { generateSeedAudio, seedConfigFromEnv } from './seed-audio.ts';
import { listStarterAudio, readStarterClip } from './starter-library.ts';
import { starterAssetId, type StarterKind } from '../shared/starter-library.ts';
import type {
  AttenuationShareSet,
  AudioBusNode,
  AudioShapingParams,
  MusicPlaylist,
  MusicSegment,
  MusicStinger,
  MusicTransition,
  RtpcDefinition,
  StateGroup,
  SwitchGroup,
} from '../shared/audio-project.ts';

interface ToolCtx {
  caller: { kind: string; id?: string };
  toolId: string;
  env?: Record<string, string | undefined>;
  cwd?: string;
  projectRoot?: string;
  game?: string;
}

function projectRootOf(ctx: ToolCtx): string {
  return ctx.projectRoot ?? ctx.env?.FORGEAX_PROJECT_ROOT ?? process.cwd();
}

function slugOf(args: { slug?: string }, ctx: ToolCtx): string {
  const slug = String(args.slug ?? ctx.game ?? '').trim();
  if (!slug) throw new BgmError('slug-required', 'slug is required (explicit; no auto-detect)', 400);
  gameRoot(projectRootOf(ctx), slug);
  return slug;
}

function audioProjectLocation(args: { slug?: string; projectId?: string }, ctx: ToolCtx) {
  const slug = slugOf(args, ctx);
  return {
    slug,
    projectId: String(args.projectId ?? slug).trim() || slug,
    gameDir: gameRoot(projectRootOf(ctx), slug),
  };
}

function asKind(v: unknown): AudioKind | undefined {
  return v === 'bgm' || v === 'sfx' || v === 'voice' ? v : undefined;
}

interface SaveGeneratedArgs {
  slug?: string;
  assetId?: string;
  name?: string;
  kind?: string;
  base64?: string;
  mimeType?: string;
  filename?: string;
  provider?: string;
  model?: string;
  shaping?: AudioShapingParams;
  prompt?: string;
}
interface AudioProjectArgs { slug?: string; projectId?: string; runtimeEvidence?: unknown }
interface PatchProjectArgs extends Partial<PatchAudioProjectArgs> { slug?: string }
interface ApplyProjectArgs extends AudioProjectArgs { expectedRevision?: number }
interface MigrateProjectArgs extends AudioProjectArgs { expectedRevision?: number }
interface DefineGameSyncToolArgs extends AudioProjectArgs {
  expectedRevision?: number;
  states?: StateGroup[];
  switches?: SwitchGroup[];
  rtpcs?: RtpcDefinition[];
}
interface DefineBusToolArgs extends AudioProjectArgs {
  expectedRevision?: number;
  buses?: AudioBusNode[];
}
interface DefineAttenuationToolArgs extends AudioProjectArgs {
  expectedRevision?: number;
  attenuations?: AttenuationShareSet[];
}
interface AuthorMusicToolArgs extends AudioProjectArgs {
  expectedRevision?: number;
  segments?: MusicSegment[];
  playlists?: MusicPlaylist[];
  transitions?: MusicTransition[];
  stingers?: MusicStinger[];
  replaceTransitions?: boolean;
}
interface GenerateAudioAssetItem {
  eventId?: string;
  assetId?: string;
  name?: string;
  kind?: string;
  prompt?: string;
  durationSeconds?: number;
  instrumental?: boolean;
  loop?: boolean;
  speed?: number;
  filename?: string;
  format?: 'mp3' | 'wav';
}
interface GenerateAudioAssetsArgs {
  slug?: string;
  concurrency?: number;
  items?: GenerateAudioAssetItem[];
}
interface ListStarterAudioArgs {
  kind?: string;
  highFrequencyOnly?: boolean;
}
interface UseStarterAudioItem {
  eventId?: string;
  starterId?: string;
  name?: string;
  filename?: string;
}
interface UseStarterAudioArgs {
  slug?: string;
  items?: UseStarterAudioItem[];
}
interface GenerateAudioPreviewArgs {
  kind?: string;
  prompt?: string;
  durationSeconds?: number;
  instrumental?: boolean;
  loop?: boolean;
  speed?: number;
  format?: 'mp3' | 'wav';
}

function generatedAssetId(slug: string, item: GenerateAudioAssetItem): string {
  if (item.assetId?.trim()) return item.assetId.trim();
  const digest = createHash('sha256')
    .update(JSON.stringify([slug, item.eventId, item.kind, item.prompt]))
    .digest('hex')
    .slice(0, 20);
  return `seed-${item.kind}-${digest}`;
}

/**
 * A finished batch is its own receipt: the bytes are on disk, in the manifest,
 * and measured. Left to infer that, callers re-derive it by hashing, globbing
 * and reading sidecars — more wall time than the generation itself — so the
 * result says outright what to call next and what not to re-check.
 */
function generationNextStep(input: { failedEventIds: string[]; warnedEventIds: string[] }): string {
  const steps = [
    'Files are already saved under gameDir and registered in audio/manifest.json. '
    + 'Draft bindings straight from the returned assetId and file; do not stat, hash, glob or read '
    + 'sidecar JSON to confirm them, and do not look for the game outside gameDir.',
    'Next call: patch-audio-project, passing archetype so cooldown, volume, spatial and rhythm '
    + 'defaults come from the server.',
  ];
  if (input.failedEventIds.length) {
    steps.push(`Regenerate only these failures, leave the rest alone: ${input.failedEventIds.join(', ')}.`);
  }
  if (input.warnedEventIds.length) {
    steps.push(
      'Too long to wire to a high-frequency event — shorten the prompt and regenerate, or move it '
      + `to rare-loot: ${input.warnedEventIds.join(', ')}.`,
    );
  }
  return steps.join(' ');
}

/** Same contract as generation, but a bad pick is re-picked, never re-prompted. */
function starterNextStep(input: { failedEventIds: string[]; warnedEventIds: string[] }): string {
  const steps = [
    'The clips are copied under gameDir and registered in audio/manifest.json. Draft bindings straight '
    + 'from the returned assetId and file; do not stat, hash or glob to confirm them, and never bind a '
    + 'path inside the plugin directory.',
    'Next call: patch-audio-project, passing archetype so cooldown, volume, spatial and rhythm defaults '
    + 'come from the server. Wire loop: true entries as looping sounds.',
  ];
  if (input.failedEventIds.length) {
    steps.push(`Re-pick only these, leave the rest alone: ${input.failedEventIds.join(', ')}.`);
  }
  if (input.warnedEventIds.length) {
    steps.push(
      'Too long for the event it landed on — pick a clip with highFrequencySafe: true, or move this one '
      + `to a rare beat: ${input.warnedEventIds.join(', ')}.`,
    );
  }
  return steps.join(' ');
}

function errorDetails(error: unknown): { code: string; error: string } {
  const value = error as { code?: unknown; message?: unknown };
  return {
    code: typeof value?.code === 'string' ? value.code : 'generation-failed',
    error: typeof value?.message === 'string' ? value.message : String(error),
  };
}

const tools = {
  'inspect-audio-events': async (args: AudioProjectArgs, ctx: ToolCtx) => {
    const { gameDir } = audioProjectLocation(args, ctx);
    return await inspectAudioEvents(gameDir);
  },

  'get-audio-project': async (args: AudioProjectArgs, ctx: ToolCtx) => {
    const { gameDir, projectId } = audioProjectLocation(args, ctx);
    const [project, applied] = await Promise.all([
      readAudioProject(gameDir, projectId),
      readAppliedAudioProject(gameDir, projectId),
    ]);
    // gameDir pins the copy to read and write; same-named games elsewhere on disk are not it.
    return { project, appliedRevision: applied?.revision ?? null, gameDir };
  },

  'patch-audio-project': async (args: PatchProjectArgs, ctx: ToolCtx) => {
    const { gameDir, projectId } = audioProjectLocation(args, ctx);
    const project = await patchAudioProject(gameDir, {
      projectId,
      expectedRevision: Number(args.expectedRevision),
      upsertBindings: args.upsertBindings,
      removeEventIds: args.removeEventIds,
    });
    const warnings = project.bindings
      .map((binding) => cooldownScopeWarning(binding))
      .filter((warning): warning is NonNullable<typeof warning> => Boolean(warning));
    return { project, warnings };
  },

  'migrate-audio-project': async (args: MigrateProjectArgs, ctx: ToolCtx) => {
    const { gameDir, projectId } = audioProjectLocation(args, ctx);
    const result = await migrateAudioProjectDraft(gameDir, {
      projectId,
      expectedRevision: Number(args.expectedRevision),
    });
    return {
      before: result.before,
      after: result.after,
      diffSummary: result.diffSummary,
      project: result.project,
    };
  },

  'define-game-sync': async (args: DefineGameSyncToolArgs, ctx: ToolCtx) => {
    const { gameDir, projectId } = audioProjectLocation(args, ctx);
    const project = await defineGameSync(gameDir, {
      projectId,
      expectedRevision: Number(args.expectedRevision),
      states: args.states,
      switches: args.switches,
      rtpcs: args.rtpcs,
    });
    return { project };
  },

  'define-bus': async (args: DefineBusToolArgs, ctx: ToolCtx) => {
    const { gameDir, projectId } = audioProjectLocation(args, ctx);
    if (!Array.isArray(args.buses) || args.buses.length === 0) {
      throw Object.assign(new Error('buses must contain at least one bus node'), { code: 'bad_input' });
    }
    const project = await defineBus(gameDir, {
      projectId,
      expectedRevision: Number(args.expectedRevision),
      buses: args.buses,
    });
    return { project };
  },

  'define-attenuation': async (args: DefineAttenuationToolArgs, ctx: ToolCtx) => {
    const { gameDir, projectId } = audioProjectLocation(args, ctx);
    if (!Array.isArray(args.attenuations) || args.attenuations.length === 0) {
      throw Object.assign(new Error('attenuations must contain at least one share set'), { code: 'bad_input' });
    }
    const project = await defineAttenuation(gameDir, {
      projectId,
      expectedRevision: Number(args.expectedRevision),
      attenuations: args.attenuations,
    });
    return { project };
  },

  'author-music': async (args: AuthorMusicToolArgs, ctx: ToolCtx) => {
    const { gameDir, projectId } = audioProjectLocation(args, ctx);
    const project = await authorMusic(gameDir, {
      projectId,
      expectedRevision: Number(args.expectedRevision),
      segments: args.segments,
      playlists: args.playlists,
      transitions: args.transitions,
      stingers: args.stingers,
      replaceTransitions: args.replaceTransitions,
    });
    return { project };
  },

  'apply-audio-project': async (args: ApplyProjectArgs, ctx: ToolCtx) => {
    const { gameDir, projectId } = audioProjectLocation(args, ctx);
    const project = await readAudioProject(gameDir, projectId);
    const expectedRevision = Number(args.expectedRevision);
    if (!Number.isInteger(expectedRevision) || expectedRevision < 0) {
      throw Object.assign(new Error('expectedRevision must be a non-negative integer'), { code: 'bad_input' });
    }
    if (project.revision !== expectedRevision) {
      throw Object.assign(
        new Error(`audio project revision changed from ${expectedRevision} to ${project.revision}`),
        { code: 'revision_conflict', actualRevision: project.revision },
      );
    }
    const runtimeSource = await readFile(
      join(ctx.cwd ?? '', 'runtime/forgeax-audio-runtime.bundle.js'),
      'utf8',
    );
    const compiled = await compileAudioRuntime(gameDir, project, runtimeSource);
    const applied = await writeAppliedAudioProject(gameDir, project);
    return { project: applied, files: compiled.files };
  },

  'generate-audio-assets': async (args: GenerateAudioAssetsArgs, ctx: ToolCtx) => {
    const slug = slugOf(args, ctx);
    const gameDir = gameRoot(projectRootOf(ctx), slug);
    const items = Array.isArray(args.items) ? args.items.slice(0, 50) : [];
    if (!items.length) {
      throw Object.assign(new Error('items must contain at least one audio request'), { code: 'bad_input' });
    }
    const concurrency = Math.min(3, Math.max(1, Math.floor(args.concurrency ?? 2)));
    const config = seedConfigFromEnv(ctx.env ?? {});
    const results: Array<Record<string, unknown>> = new Array(items.length);
    let cursor = 0;

    const worker = async () => {
      while (cursor < items.length) {
        const index = cursor++;
        const item = items[index]!;
        const eventId = String(item.eventId ?? '').trim();
        const kind = asKind(item.kind);
        const assetId = generatedAssetId(slug, item);
        try {
          if (!eventId) throw Object.assign(new Error('eventId is required'), { code: 'bad_input' });
          if (!kind) throw Object.assign(new Error("kind must be 'bgm', 'sfx', or 'voice'"), { code: 'invalid-kind' });
          if (!item.prompt?.trim()) throw Object.assign(new Error('prompt is required'), { code: 'invalid-prompt' });
          const generated = await generateSeedAudio(config, {
            kind,
            prompt: item.prompt,
            durationSeconds: item.durationSeconds,
            instrumental: item.instrumental,
            loop: item.loop,
            speed: item.speed,
            format: item.format,
          });
          const attached = await attachGeneratedAudio({
            projectRoot: projectRootOf(ctx),
            slug,
            assetId,
            name: String(item.name ?? '').trim() || eventId,
            kind,
            base64: generated.bytes.toString('base64'),
            mimeType: generated.mimeType,
            filename: item.filename,
            provider: 'seed-audio',
            model: generated.model,
            addedBy: ctx.caller?.kind === 'ai' ? 'ai' : 'human',
            eventId,
            ...(item.prompt?.trim() ? { prompt: item.prompt.trim() } : {}),
          });
          results[index] = {
            ok: true,
            eventId,
            assetId,
            kind,
            file: attached.file,
            bytes: attached.bytes,
            reused: attached.reused,
            traceId: generated.traceId,
            model: generated.model,
            ...(typeof attached.durationMs === 'number' ? { durationMs: attached.durationMs } : {}),
            ...(attached.durationWarning ? { durationWarning: attached.durationWarning } : {}),
          };
        } catch (error) {
          results[index] = { ok: false, eventId, assetId, kind: item.kind, ...errorDetails(error) };
        }
      }
    };
    await Promise.all(Array.from({ length: Math.min(concurrency, items.length) }, worker));
    const generated = results.filter((result) => result.ok === true).length;
    const eventIdsWhere = (predicate: (result: Record<string, unknown>) => boolean): string[] =>
      results.filter(predicate).map((result) => String(result.eventId ?? '')).filter(Boolean);
    return {
      ok: generated === items.length,
      slug,
      gameDir,
      summary: { total: items.length, generated, failed: items.length - generated },
      results,
      nextStep: generationNextStep({
        failedEventIds: eventIdsWhere((result) => result.ok !== true),
        warnedEventIds: eventIdsWhere((result) => typeof result.durationWarning === 'string'),
      }),
    };
  },

  /**
   * The catalog of clips packaged with the plugin. Read-only and unfiltered
   * beyond kind, so it stays a pick-list: choosing still means copying bytes
   * into the game through `use-starter-audio`.
   */
  'list-starter-audio': async (args: ListStarterAudioArgs, ctx: ToolCtx) => {
    const kind = args.kind === 'sfx' || args.kind === 'bgm' ? (args.kind as StarterKind) : undefined;
    const entries = await listStarterAudio(ctx.cwd ?? '', {
      ...(kind ? { kind } : {}),
      ...(args.highFrequencyOnly === true ? { highFrequencyOnly: true } : {}),
    });
    return {
      total: entries.length,
      entries,
      nextStep:
        'These clips ship with the plugin and are not in any game yet. Call use-starter-audio with '
        + 'the ids you want; it copies the bytes into the game and registers them, then continue with '
        + 'patch-audio-project as usual. Prefer generate-audio-assets when the game needs something '
        + 'specific and Seed Audio is configured. Clips with highFrequencySafe: false must not go on '
        + 'impact, pickup, ui or footstep events, and ambient: true clips belong on scene loops.',
    };
  },

  /**
   * Copies packaged clips into the game so the starter pack obeys the same rule
   * as generation: nothing plays from inside the plugin. Output shape matches
   * `generate-audio-assets` so the binding steps after it are identical.
   */
  'use-starter-audio': async (args: UseStarterAudioArgs, ctx: ToolCtx) => {
    const slug = slugOf(args, ctx);
    const gameDir = gameRoot(projectRootOf(ctx), slug);
    const items = Array.isArray(args.items) ? args.items.slice(0, 50) : [];
    if (!items.length) {
      throw Object.assign(new Error('items must contain at least one starter pick'), { code: 'bad_input' });
    }

    const results: Array<Record<string, unknown>> = [];
    for (const item of items) {
      const eventId = String(item.eventId ?? '').trim();
      const starterId = String(item.starterId ?? '').trim();
      try {
        if (!eventId) throw Object.assign(new Error('eventId is required'), { code: 'bad_input' });
        const { entry, bytes } = await readStarterClip(ctx.cwd ?? '', starterId);
        const assetId = starterAssetId(entry.id);
        const attached = await attachGeneratedAudio({
          projectRoot: projectRootOf(ctx),
          slug,
          assetId,
          name: String(item.name ?? '').trim() || entry.usage || eventId,
          kind: entry.kind,
          base64: bytes.toString('base64'),
          mimeType: entry.mime,
          filename: item.filename,
          provider: 'starter-library',
          model: 'starter',
          addedBy: ctx.caller?.kind === 'ai' ? 'ai' : 'human',
          eventId,
          prompt: `starter:${entry.id}${entry.usage ? ` · ${entry.usage}` : ''}`,
        });
        results.push({
          ok: true,
          eventId,
          starterId: entry.id,
          assetId,
          kind: entry.kind,
          file: attached.file,
          bytes: attached.bytes,
          reused: attached.reused,
          usage: entry.usage,
          loop: entry.loop === true,
          ...(entry.ambient ? { ambient: true } : {}),
          ...(typeof attached.durationMs === 'number' ? { durationMs: attached.durationMs } : {}),
          ...(attached.durationWarning ? { durationWarning: attached.durationWarning } : {}),
        });
      } catch (error) {
        results.push({ ok: false, eventId, starterId, ...errorDetails(error) });
      }
    }

    const applied = results.filter((result) => result.ok === true).length;
    const eventIdsWhere = (predicate: (result: Record<string, unknown>) => boolean): string[] =>
      results.filter(predicate).map((result) => String(result.eventId ?? '')).filter(Boolean);
    return {
      ok: applied === items.length,
      slug,
      gameDir,
      summary: { total: items.length, applied, failed: items.length - applied },
      results,
      nextStep: starterNextStep({
        failedEventIds: eventIdsWhere((result) => result.ok !== true),
        warnedEventIds: eventIdsWhere((result) => typeof result.durationWarning === 'string'),
      }),
    };
  },

  'verify-audio-project': async (args: AudioProjectArgs, ctx: ToolCtx) => {
    const { gameDir, projectId } = audioProjectLocation(args, ctx);
    const project = await readAppliedAudioProject(gameDir, projectId)
      ?? await readAudioProject(gameDir, projectId);
    return await verifyAudioProject(gameDir, project, {
      requireRuntime: project.status === 'applied',
      ...(args.runtimeEvidence !== undefined ? { runtimeEvidence: args.runtimeEvidence } : {}),
    });
  },

  /**
   * Audition-only generation for the creative audio studio. Unlike
   * `generate-audio-assets` this returns the bytes instead of writing them:
   * the audio studio plays several takes and only the one the user keeps is
   * persisted, through `save-generated-audio`. No slug, no game writes.
   */
  'generate-audio-preview': async (args: GenerateAudioPreviewArgs, ctx: ToolCtx) => {
    const kind = asKind(args.kind);
    if (!kind) {
      throw Object.assign(new Error("kind must be 'bgm', 'sfx', or 'voice'"), { code: 'invalid-kind' });
    }
    if (!args.prompt?.trim()) {
      throw Object.assign(new Error('prompt is required'), { code: 'invalid-prompt' });
    }
    const generated = await generateSeedAudio(seedConfigFromEnv(ctx.env ?? {}), {
      kind,
      prompt: args.prompt,
      durationSeconds: args.durationSeconds,
      instrumental: args.instrumental,
      loop: args.loop,
      speed: args.speed,
      format: args.format,
    });
    return {
      kind,
      base64: generated.bytes.toString('base64'),
      mimeType: generated.mimeType,
      provider: 'seed-audio',
      model: generated.model,
      traceId: generated.traceId,
      fileSizeBytes: generated.bytes.byteLength,
    };
  },

  /**
   * Lets the audio studio disable generation with a real reason instead of
   * failing per take. `ctx.env` is filtered to the manifest's `requestedEnv`,
   * so this only ever reports on the plugin's own credentials.
   */
  'get-audio-provider-status': async (_args: Record<string, never>, ctx: ToolCtx) => {
    const config = seedConfigFromEnv(ctx.env ?? {});
    return {
      seed: {
        configured: Boolean(config.headerValue),
        model: config.model,
      },
    };
  },

  'save-generated-audio': async (args: SaveGeneratedArgs, ctx: ToolCtx) => {
    const kind = asKind(args.kind);
    if (!kind) {
      throw Object.assign(new Error("kind must be 'bgm', 'sfx', or 'voice'"), { code: 'invalid-kind' });
    }
    return await attachGeneratedAudio({
      projectRoot: projectRootOf(ctx),
      slug: args.slug,
      assetId: args.assetId ?? '',
      name: args.name ?? '',
      kind,
      base64: args.base64 ?? '',
      mimeType: args.mimeType,
      filename: args.filename,
      provider: args.provider,
      model: args.model,
      shaping: args.shaping,
      prompt: args.prompt,
      addedBy: ctx.caller?.kind === 'ai' ? 'ai' : 'human',
    });
  },
};

// Source lives in server/, while the published backend lives in dist/server/.
const backendParent = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const pluginDir = existsSync(join(backendParent, 'forgeax-extension.json'))
  ? backendParent
  : resolve(backendParent, '..');

// Extension Host selects the default export and calls tools[id](context, args).
// Orchestrator and standalone Vite call the direct handlers as (args, ctx).
const hostTools = Object.fromEntries(Object.entries(tools).map(([toolId, handler]) => [
  toolId,
  (context: { gameId: string; gameRoot: string }, args: unknown) => {
    const projectRoot = resolve(context.gameRoot, '..', '..', '..');
    return (handler as (args: unknown, ctx: ToolCtx) => unknown)(args, {
      caller: { kind: 'user' },
      toolId,
      projectRoot,
      game: context.gameId,
      cwd: pluginDir,
      env: {
        FORGEAX_PROJECT_ROOT: projectRoot,
        SEED_AUDIO_API_KEY: process.env.SEED_AUDIO_API_KEY,
        SEED_AUDIO_ENDPOINT: process.env.SEED_AUDIO_ENDPOINT,
        SEED_AUDIO_MODEL: process.env.SEED_AUDIO_MODEL,
      },
    });
  },
]));

export default Object.assign({}, tools, { tools: hostTools });
