/**
 * Public audio-project surface.
 *
 * Canonical schema is forgeax-audio-project/2. v1 documents are accepted by
 * `normalizeAudioProject` and migrated automatically. The derived `bindings`
 * array on `AudioProject` keeps the current audio studio and runtime compiler
 * working until those layers move to objects/events.
 */
export {
  AUDIO_PROJECT_SCHEMA_V1,
  AudioProjectError,
  audioBindingAssets,
  isSafeAudioEventId,
  type AudioAssetRef,
  type AudioBinding,
  type AudioBus,
  type AudioCondition,
  type AudioConditionOperator,
  type AudioConditionValue,
  type AudioFollowCase,
  type AudioFollowRange,
  type AudioFollowRule,
  type AudioFollowValue,
  type AudioHookProvenance,
  type AudioHookStatus,
  type AudioKind,
  type AudioPlaybackMode,
  type AudioProjectErrorCode,
  type AudioProjectV1,
  type AudioShapingParams,
  type AudioSpatialMode,
  type AudioVariationMode,
} from './audio-project-v1.ts';

export {
  AUDIO_ENGINE_VERSION,
  AUDIO_PROJECT_SCHEMA,
  attachLegacyBindings,
  audioProjectAssets,
  bindingsFromV2,
  defaultBuses,
  emptyAudioProject,
  emptyMusicProject,
  gainDbToVolume,
  migrateV1ToV2,
  normalizeAudioProject,
  normalizeAudioProjectV2,
  stableEntityId,
  toProjectDocument,
  volumeToGainDb,
  type AttenuationShareSet,
  type AudioAction,
  type AudioBusNode,
  type AudioEvent,
  type AudioNode,
  type AudioObject,
  type AudioProject,
  type AudioProjectDocument,
  type BlendLayer,
  type CurveInterp,
  type CurvePoint,
  type MusicPlaylist,
  type MusicProject,
  type MusicSegment,
  type MusicStinger,
  type MusicSyncPoint,
  type MusicTrack,
  type MusicTrackClip,
  type MusicTransition,
  type RtpcBinding,
  type RtpcDefinition,
  type SelectionScope,
  type StateGroup,
  type StateOffset,
  type SwitchGroup,
} from './audio-project-v2.ts';
