#!/usr/bin/env node
/**
 * Bundle runtime/ into a single ESM file that apply-audio-project writes into games.
 */
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { generateDtsBundle } from 'dts-bundle-generator';
import { spawnSync } from 'node:child_process';

const pluginDir = join(dirname(fileURLToPath(import.meta.url)), '..');
const entry = join(pluginDir, 'runtime/index.ts');
// Keep the artifact beside the sources — `dist/` is reserved for the Vite UI
// build and is gitignored, but apply-audio-project must be able to read this
// file from a freshly cloned tree.
const outFile = join(pluginDir, 'runtime/forgeax-audio-runtime.bundle.js');

const BANNER = [
  '/* forgeax-audio-runtime — generated by scripts/build-runtime.mjs; do not edit */',
  '/* Source entry: runtime/index.ts */',
  '',
].join('\n');

await mkdir(dirname(outFile), { recursive: true });

const bun = process.env.BUN_BIN || 'bun';
const result = spawnSync(
  bun,
  ['build', entry, '--outfile', outFile, '--format', 'esm', '--target', 'browser'],
  { encoding: 'utf8' },
);

if (result.error || result.status !== 0) {
  // spawn errors leave stdout/stderr empty; without this the usual failure —
  // bun not being on PATH — reads as a compile error and gets debugged as one.
  process.stderr.write(
    result.error
      ? `cannot run "${bun}": ${result.error.message}\nSet BUN_BIN if bun lives outside PATH.\n`
      : result.stderr || result.stdout || 'bun build failed\n',
  );
  process.exit(result.status ?? 1);
}

// Pin a stable banner so the bake step always writes the same preamble.
const built = await readFile(outFile, 'utf8');
const normalized = `${BANNER}${built.endsWith('\n') ? built : `${built}\n`}`;
await writeFile(outFile, normalized, 'utf8');

process.stdout.write(`built ${outFile} (${Buffer.byteLength(normalized)} bytes)\n`);

const [declarations] = generateDtsBundle([{ filePath: entry, output: { noBanner: true } }], {
  preferredConfigPath: join(pluginDir, 'tsconfig.runtime.json'),
});
await writeFile(join(pluginDir, 'runtime/forgeax-audio-runtime.bundle.d.ts'), declarations, 'utf8');
